"""
run_pipeline_infinigen.py
Standalone Blender-headless pipeline for curating a single Infinigen seed scene.

Usage (via shell wrapper — recommended):
    bash run_pipeline_infinigen.sh /path/to/seed_folder

Usage (direct):
    blender --background --factory-startup --python run_pipeline_infinigen.py -- /path/to/seed_folder

Input:
    A seed folder generated by Infinigen, containing:
        <seed>/fine/scene.blend
        <seed>/coarse/solve_state.json

Output:
    <seed>/output/
        parameters_<seed>.json
        all_<seed>.json
        render_topdown_<seed>.png
        render_topdown_annotated_<seed>.png
        main_objects/render_main_objects_<seed>.png  (+ per-object views)
        render_oblique_<seed>_oblique_0..3.png
        floormask_<seed>.png
        description/description_topdown.txt          (requires OpenAI API key)
"""

import bpy
import os
import sys
import json
import base64
import bmesh
import time
import traceback
from mathutils import Vector


# =============================================================================
# [USER CONFIG] OpenAI API settings for Step 6 (LLM scene description)
#
# Option A — .env file:
#   Create a file named ".env" in the same directory as this script with:
#       OPENAI_API_KEY=sk-xxxxxxxxxxxxxxxxxxxxxxxx
#       OPENAI_BASE_URL=https://your-proxy.example.com/v1   # optional
#       OPENAI_MODEL=gpt-4o                                 # optional
#
# Option B — Environment variables:
#   export OPENAI_API_KEY="sk-xxxxxxxxxxxxxxxxxxxxxxxx"
#   export OPENAI_BASE_URL="https://your-proxy.example.com/v1"  # optional
#   export OPENAI_MODEL="gpt-4o"                                # optional
#
# If you are in a region where OpenAI is not directly accessible, you MUST set
# OPENAI_BASE_URL to an API-compatible relay/proxy endpoint.
#
# If no API key is found, Step 6 is gracefully skipped.
# =============================================================================

# Name of the .env file (looked up relative to this script's directory)
_ENV_FILE_NAME = ".env"


# =============================================================================
# Timing helpers
# =============================================================================
_pipeline_start = time.time()
_step_timings = []


def _fmt_elapsed(seconds):
    m, s = divmod(int(seconds), 60)
    return f"{m}m {s}s" if m > 0 else f"{s}s"


def _print_step_header(step_num, total, title, details=None):
    elapsed = time.time() - _pipeline_start
    print(f"\n{'='*60}")
    print(f"[Step {step_num}/{total}] {title}  (elapsed: {_fmt_elapsed(elapsed)})")
    if details:
        for line in details:
            print(f"  {line}")
    print(f"{'='*60}")
    sys.stdout.flush()


def _print_step_done(step_num, title, start_time, extra_msg=""):
    elapsed = time.time() - start_time
    _step_timings.append((step_num, title, elapsed))
    msg = f"[Step {step_num} Done] {title} — {_fmt_elapsed(elapsed)}"
    if extra_msg:
        msg += f"  {extra_msg}"
    print(msg)
    sys.stdout.flush()


# =============================================================================
# Parse CLI args (everything after "--")
# =============================================================================
argv = sys.argv
if "--" in argv:
    argv = argv[argv.index("--") + 1:]
else:
    argv = []

if len(argv) < 1:
    print("Usage: blender --background --factory-startup "
          "--python run_pipeline_infinigen.py -- <seed_folder>")
    sys.exit(1)

SEED_FOLDER = os.path.abspath(argv[0])
SEED = os.path.basename(SEED_FOLDER)

BLEND_FILE = os.path.join(SEED_FOLDER, "fine", "scene.blend")
SOLVE_STATE = os.path.join(SEED_FOLDER, "coarse", "solve_state.json")
OUTPUT_DIR = os.path.join(SEED_FOLDER, "output")

# Add project root to sys.path so we can import render / util
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from util import (
    is_point_in_polygon,
    compute_bbox,
    get_world_aabb,
    get_obb_corners,
    render_scene,
)
from render import (
    find_filled_floor_by_location,
    is_within_threshold,
    render_topdown,
    render_oblique,
    setup_topdown_camera,
    setup_render_settings,
)


# =============================================================================
# Validate inputs
# =============================================================================
def validate():
    errors = []
    if not os.path.isdir(SEED_FOLDER):
        errors.append(f"Seed folder not found: {SEED_FOLDER}")
    if not os.path.isfile(BLEND_FILE):
        errors.append(f"scene.blend not found: {BLEND_FILE}")
    if not os.path.isfile(SOLVE_STATE):
        errors.append(f"solve_state.json not found: {SOLVE_STATE}")
    if errors:
        for e in errors:
            print(f"[Error] {e}")
        sys.exit(1)


# =============================================================================
# Scene parameter extraction (inlined from manage_tasks.py to avoid top-level
# imports of dotenv/openai which may not be installed yet)
# =============================================================================
def export_scene_parameters(blend_file_path, output_json_path):
    if os.path.exists(output_json_path):
        print(f"[Skip] Already exists: {output_json_path}")
        return
    if bpy.data.filepath != blend_file_path:
        bpy.ops.wm.open_mainfile(filepath=blend_file_path)

    skip_keywords = [
        "skirting", "doors", "windows", "room_wall", "room_floor",
        "room_ceiling", "room_exterior", "staircases", "door_casings"
    ]

    filled_floor = find_filled_floor_by_location()

    doors, windows = [], []
    bm = bmesh.new()
    bm.from_mesh(filled_floor.data)
    bm.transform(filled_floor.matrix_world)
    up_vector = Vector((0, 0, 1))

    for obj in bpy.data.objects:
        if obj.type != 'MESH':
            continue
        _, _, _, center = compute_bbox([obj])
        point = (center.x, center.y)
        for col in obj.users_collection:
            for face in bm.faces:
                if face.normal.dot(up_vector) > 0.9:
                    verts_2d = [Vector((v.co.x, v.co.y)) for v in face.verts]
                    if col.name == "unique_assets:doors":
                        if is_point_in_polygon(point, verts_2d) or \
                           is_within_threshold(point, verts_2d, threshold=1.0):
                            doors.append(obj)
                    if col.name == "unique_assets:windows":
                        if is_point_in_polygon(point, verts_2d) or \
                           is_within_threshold(point, verts_2d, threshold=1.0):
                            windows.append(obj)

    export_data = []
    for obj in bpy.data.objects:
        if obj.type != 'MESH':
            continue
        name_low = obj.name.lower()
        if obj not in doors and obj not in windows:
            if any(kw in name_low for kw in skip_keywords):
                continue
            if not any(col.name == "unique_assets" for col in obj.users_collection):
                continue
            if "CeilingLight" in obj.name:
                continue
            if len(obj.data.vertices) < 3:
                continue

        local_bbox = [Vector(corner) for corner in obj.bound_box]
        min_local = [min(v[i] for v in local_bbox) for i in range(3)]
        max_local = [max(v[i] for v in local_bbox) for i in range(3)]
        min_world, max_world = get_world_aabb(obj)

        export_data.append({
            "name": obj.name,
            "type": obj.type,
            "location": [
                (min_world[0] + max_world[0]) / 2,
                (min_world[1] + max_world[1]) / 2,
                min_world[2],
            ],
            "rotation": list(obj.rotation_euler),
            "scale": list(obj.scale),
            "dimensions": list(obj.dimensions),
            "visible": obj.visible_get(),
            "materials": [s.material.name for s in obj.material_slots if s.material],
            "aabb_local": {"min": min_local, "max": max_local},
            "aabb_world": {"min": min_world, "max": max_world},
            "matrix_world": [list(row) for row in obj.matrix_world],
            "obb": get_obb_corners(obj),
            "mesh": {
                "vertices": len(obj.data.vertices),
                "edges": len(obj.data.edges),
                "polygons": len(obj.data.polygons),
            },
        })

    os.makedirs(os.path.dirname(output_json_path), exist_ok=True)
    with open(output_json_path, "w") as f:
        json.dump(export_data, f, indent=4)
    print(f"  Exported {len(export_data)} objects")


def merge_parameters_and_solve(parameters_path, solve_state_path, output_path):
    if os.path.exists(output_path):
        print(f"[Skip] Already exists: {output_path}")
        return
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(parameters_path) as f:
        params = json.load(f)
    with open(solve_state_path) as f:
        solve_objs = json.load(f).get("objs", {})

    merged = []
    for p in params:
        name = p.get("name", "")
        if "window" in name.lower() or "door" in name.lower():
            merged.append(p.copy())
            continue
        for sv in solve_objs.values():
            if sv.get("obj") == name:
                entry = p.copy()
                entry.update({k: v for k, v in sv.items() if k != "obj"})
                merged.append(entry)
                break

    with open(output_path, "w") as f:
        json.dump(merged, f, indent=4)
    print(f"  parameters: {len(params)} | solve_state: {len(solve_objs)} | merged: {len(merged)}")


# =============================================================================
# Pipeline steps
# =============================================================================
TOTAL_STEPS = 6


def step1_export_parameters():
    path = os.path.join(OUTPUT_DIR, f"parameters_{SEED}.json")
    _print_step_header(1, TOTAL_STEPS, "Exporting scene parameters", [
        f"Input:  {BLEND_FILE}",
        f"Output: {path}",
    ])
    t0 = time.time()
    export_scene_parameters(BLEND_FILE, path)
    _print_step_done(1, "Export parameters", t0)
    return path


def step2_merge_parameters(params_path):
    path = os.path.join(OUTPUT_DIR, f"all_{SEED}.json")
    _print_step_header(2, TOTAL_STEPS, "Merging parameters + solve_state", [
        f"Input:  {params_path}",
        f"        {SOLVE_STATE}",
        f"Output: {path}",
    ])
    t0 = time.time()
    merge_parameters_and_solve(params_path, SOLVE_STATE, path)
    _print_step_done(2, "Merge parameters", t0)
    return path


def step3_render_topdown(merged_json):
    path = os.path.join(OUTPUT_DIR, f"render_topdown_{SEED}.png")
    _print_step_header(3, TOTAL_STEPS, "Rendering top-down + annotated + main objects", [
        f"Input:  {BLEND_FILE}",
        f"        {merged_json}",
        f"Output: {path}  (+ annotated + main_objects/)",
    ])
    t0 = time.time()
    bpy.ops.wm.read_factory_settings(use_empty=True)
    render_topdown(BLEND_FILE, path, merged_json, render_main_objects=True)
    _print_step_done(3, "Top-down render", t0)


def step4_render_oblique(merged_json):
    base = os.path.join(OUTPUT_DIR, f"render_oblique_{SEED}")
    _print_step_header(4, TOTAL_STEPS, "Rendering oblique views", [
        f"Input:  {BLEND_FILE}",
        f"Output: {base}_oblique_0..3.png",
    ])
    t0 = time.time()
    bpy.ops.wm.read_factory_settings(use_empty=True)
    render_oblique(BLEND_FILE, base, merged_json)
    _print_step_done(4, "Oblique render", t0)


def step5_render_floormask():
    path = os.path.join(OUTPUT_DIR, f"floormask_{SEED}.png")
    _print_step_header(5, TOTAL_STEPS, "Rendering floor mask", [
        f"Input:  {BLEND_FILE}",
        f"Output: {path}",
    ])
    t0 = time.time()

    if os.path.exists(path):
        print(f"[Skip] Already exists: {path}")
        _print_step_done(5, "Floor mask", t0, "(skipped)")
        return

    bpy.ops.wm.read_factory_settings(use_empty=True)
    bpy.ops.wm.open_mainfile(filepath=BLEND_FILE)

    floor_obj = find_filled_floor_by_location()

    mat = bpy.data.materials.new(name="WhiteMaskMaterial")
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    for node in nodes:
        nodes.remove(node)
    emission = nodes.new(type='ShaderNodeEmission')
    emission.inputs[0].default_value = (1, 1, 1, 1)
    out_node = nodes.new(type='ShaderNodeOutputMaterial')
    links.new(emission.outputs[0], out_node.inputs[0])
    floor_obj.active_material = mat

    wall_and_floor = [floor_obj]
    room_prefix = floor_obj.name.replace('.floor', '')
    for obj in bpy.data.objects:
        if obj.name != floor_obj.name:
            obj.hide_render = True
        if obj.name == f"{room_prefix}.wall":
            wall_and_floor.append(obj)

    bpy.context.scene.render.filepath = path
    bpy.context.scene.render.image_settings.file_format = 'PNG'
    bpy.context.scene.render.image_settings.color_mode = 'BW'
    bpy.context.scene.render.film_transparent = False

    scene = bpy.context.scene
    scene.world.use_nodes = True
    bg = scene.world.node_tree.nodes.get("Background")
    if bg:
        bg.inputs[0].default_value = (0, 0, 0, 1)

    cam = setup_topdown_camera(wall_and_floor, floor_obj)
    scene.camera = cam
    setup_render_settings(path, (1024, 1024), 1)
    render_scene()
    bpy.data.objects.remove(cam, do_unlink=True)
    _print_step_done(5, "Floor mask", t0)


def step6_generate_description():
    _print_step_header(6, TOTAL_STEPS, "Generating LLM scene description", [
        f"Config: {_ENV_FILE_NAME} (OPENAI_API_KEY, OPENAI_BASE_URL, OPENAI_MODEL)",
    ])
    t0 = time.time()

    # --- Load API config ---
    try:
        from dotenv import load_dotenv
        env_path = os.path.join(PROJECT_ROOT, _ENV_FILE_NAME)
        if os.path.isfile(env_path):
            load_dotenv(env_path)
    except ImportError:
        print("[Skip] python-dotenv not installed — skipping")
        _print_step_done(6, "LLM description", t0, "(skipped)")
        return

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        print(f"[Skip] OPENAI_API_KEY not set (checked env + {_ENV_FILE_NAME})")
        _print_step_done(6, "LLM description", t0, "(skipped — no key)")
        return

    # Optional: relay endpoint and model name
    base_url = os.getenv("OPENAI_BASE_URL")        # e.g. https://relay.example.com/v1
    model = os.getenv("OPENAI_MODEL", "gpt-4o")    # default: gpt-4o

    desc_dir = os.path.join(OUTPUT_DIR, "description")
    os.makedirs(desc_dir, exist_ok=True)
    desc_path = os.path.join(desc_dir, "description_topdown.txt")

    if os.path.exists(desc_path):
        print(f"[Skip] Already exists: {desc_path}")
        _print_step_done(6, "LLM description", t0, "(skipped)")
        return

    # --- Check required images ---
    img_topdown = os.path.join(OUTPUT_DIR, f"render_topdown_annotated_{SEED}.png")
    img_oblique = os.path.join(OUTPUT_DIR, f"render_oblique_{SEED}_oblique_0.png")
    img_main    = os.path.join(OUTPUT_DIR, "main_objects", f"render_main_objects_{SEED}.png")

    missing = []
    for p, label in [(img_topdown, "annotated topdown"),
                     (img_oblique, "oblique view"),
                     (img_main, "main objects")]:
        if not os.path.exists(p):
            missing.append(f"  - {label}: {p}")
    if missing:
        print("[Skip] Missing required images:")
        for m in missing:
            print(m)
        _print_step_done(6, "LLM description", t0, "(skipped — missing images)")
        return

    # --- Prompt ---
    prompt = (
        "You are an interior layout analyst. Analyze the provided top-down view, oblique view of the room, "
        "and four side views and a top-down view of major objects potentially containing small objects, and output a structured JSON description. "
        "Your task is to describe the room in detail for training a 2D-to-3D room generation model. "
        "Base your analysis strictly on the visual content. Avoid any uncertain or speculative expressions like 'appears to be', 'might be', 'likely', or 'a possible'. "
        "Only describe what is clearly visible, and express all content as complete English sentences. Do not use single words or fragments. "
        "Your output must follow the exact JSON format below, where each value is a list of complete sentences in English. If a section is not applicable, use an empty list. "
        "The categories are as follows:\n\n"
        "{\n"
        '  "global_description": {\n'
        '    "room_type": [],\n'
        '    "style": [],\n'
        '    "shape_and_size": [],\n'
        '    "local_density": [],\n'
        '    "symmetry": [],\n'
        '    "functional_zones": []\n'
        '  },\n'
        '  "large_objects_description": {\n'
        '    "summary": [],\n'
        '    "abosolute_arrangement": [],\n'
        '    "relative_positions": []\n'
        '  },\n'
        '  "small_objects_description": {\n'
        '    "summary": [],\n'
        '    "on_surfaces": [],\n'
        '    "on_shelves": [],\n'
        '    "distribution_and_pattern": []\n'
        '  }\n'
        "}\n\n"
        "Do not include any explanation or extra text. Only output the JSON object as described above."
    )

    # --- Call API ---
    try:
        from openai import OpenAI

        client_kwargs = {"api_key": api_key}
        if base_url:
            client_kwargs["base_url"] = base_url
            print(f"  Using base_url: {base_url}")
        print(f"  Model: {model}")

        client = OpenAI(**client_kwargs)

        def _read_b64(p):
            with open(p, "rb") as f:
                return base64.b64encode(f.read()).decode("utf-8")

        print(f"  Sending 3 images to {model}...")
        sys.stdout.flush()

        response = client.chat.completions.create(
            model=model,
            messages=[{
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{_read_b64(img_topdown)}"}},
                    {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{_read_b64(img_oblique)}"}},
                    {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{_read_b64(img_main)}"}},
                ],
            }],
            max_tokens=800,
        )

        text = response.choices[0].message.content.strip()
        with open(desc_path, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"  Saved: {desc_path}")
        _print_step_done(6, "LLM description", t0)

    except ImportError:
        print("[Skip] openai package not installed")
        _print_step_done(6, "LLM description", t0, "(skipped)")
    except Exception as e:
        print(f"[Error] {e}")
        traceback.print_exc()
        _print_step_done(6, "LLM description", t0, "(FAILED)")


# =============================================================================
# Main
# =============================================================================
def main():
    print(f"\n{'#'*60}")
    print(f"# Infinigen Data Curation Pipeline")
    print(f"# Seed:   {SEED}")
    print(f"# Input:  {SEED_FOLDER}")
    print(f"# Output: {OUTPUT_DIR}")
    print(f"{'#'*60}")

    validate()
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Steps 1-2 are fatal (later steps depend on their output)
    try:
        params_path = step1_export_parameters()
    except Exception as e:
        print(f"\n[FATAL] Step 1 failed: {e}")
        traceback.print_exc()
        sys.exit(1)

    try:
        merged_json = step2_merge_parameters(params_path)
    except Exception as e:
        print(f"\n[FATAL] Step 2 failed: {e}")
        traceback.print_exc()
        sys.exit(1)

    # Steps 3-6 are non-fatal (pipeline continues on error)
    for fn, label in [
        (lambda: step3_render_topdown(merged_json), "Step 3"),
        (lambda: step4_render_oblique(merged_json),  "Step 4"),
        (lambda: step5_render_floormask(),            "Step 5"),
        (lambda: step6_generate_description(),        "Step 6"),
    ]:
        try:
            fn()
        except Exception as e:
            print(f"\n[Error] {label} failed: {e}")
            traceback.print_exc()

    # --- Final report ---
    total = time.time() - _pipeline_start
    print(f"\n{'#'*60}")
    print(f"# Pipeline Complete!  Total: {_fmt_elapsed(total)}")
    print(f"# Output: {OUTPUT_DIR}")
    print(f"#")
    print(f"# Timing breakdown:")
    for num, title, elapsed in _step_timings:
        print(f"#   Step {num}: {title:<25s} {_fmt_elapsed(elapsed):>8s}")
    print(f"#   {'─'*40}")
    print(f"#   Total:{'':26s} {_fmt_elapsed(total):>8s}")
    print(f"#")
    print(f"# Output files:")
    if os.path.isdir(OUTPUT_DIR):
        for root, dirs, files in os.walk(OUTPUT_DIR):
            for fname in sorted(files):
                rel = os.path.relpath(os.path.join(root, fname), OUTPUT_DIR)
                sz = os.path.getsize(os.path.join(root, fname))
                if sz > 1024 * 1024:
                    s = f"{sz / 1024 / 1024:.1f} MB"
                elif sz > 1024:
                    s = f"{sz / 1024:.0f} KB"
                else:
                    s = f"{sz} B"
                print(f"#   {rel:<50s} {s:>8s}")
    print(f"{'#'*60}")


if __name__ == "__main__":
    main()
else:
    main()
